# fichier de configuration ansible, sans amelioration .
- hosts: localhost
  remote_user: root
  tasks:

# suppression de la connexion nommer "wired connexion 1"
  - name: Suppression de la connexion nommer "wired connexion 1"
    shell: nmcli connection del "Wired connection 1"
    ignore_errors: true

# suppression de la connexion nommer "wired connexion 1"
  - name: Suppression de la connexion nommer "wired connexion 2"
    shell: nmcli connection del "Wired connection 2"
    ignore_errors: true

  # - name: Suppression de la passerelle par défaut
  #   shell: ip route del default || true
  #   ignore_errors: true

  - name: Configuration de VM1/eth1
    nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      state: present
      autoconnect: true
      ip4: 172.16.2.131/28
      method6: disabled

  - name: Configuration de VM1/eth2
    community.general.nmcli:	
      type: ethernet
      conn_name: eth2 via ansible
      ifname: eth2
      state: present
      ip6: fc00:1234:3::1/64
      method4: disabled

  - name: Configuration de la route vers LAN2 via VM2
    community.general.nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      routes4: 172.16.2.160/28  172.16.2.132 
      state: present

  - name: Activation du routage IPv6
    sysctl:
      name: net.ipv6.conf.all.forwarding
      value: '1'
      sysctl_set: yes

  - name: Activation explicite de cette configuration eth1
    shell: nmcli con up "eth1 via ansible"

  - name: Activation explicite de cette configuration eth2
    shell: nmcli con up "eth2 via ansible"

