# -*- coding: utf-8 -*-
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

##### Vos Configurations
  config.vm.box = "m1reseaux"

  # Ajout du port forwarding sur l'interface eth0, rendre la ligne suivant executable si la config ansible utilisé est la verssion avec les ameliorations
  #config.vm.network "forwarded_port", guest: 123, host: 8080
  
  # Ajout d'une interface réseau (privée)
  config.vm.network "private_network", ip:"0.0.0.0", auto_config: false, virtualbox__intnet: "LAN1" 
  config.vm.network "private_network", ip:"0.0.0.0", auto_config: false, virtualbox__intnet: "LAN3-6"

##### NE PAS MODIFIER CETTE PARTIE
  config.vm.hostname = File.basename(Dir.getwd)

  ### Dossiers partagés
  config.vm.synced_folder ".", "/vagrant", owner: "m1reseaux"
  config.vm.synced_folder "../partage", "/mnt/partage", create: true, owner: "m1reseaux" 

  # paramètres virtualbox
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true  # performance
    # Commenter pour s'exécuter sans GUI
    vb.gui = true
    # Mémoire
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--vram", "16"]

    # Copier coller, pour virtualbox >= 6.1
    vb.customize 'post-boot', ['controlvm', :id, 'clipboard', 'mode', 'bidirectional']
  end
  
  # execution de scprit au demarage des vm.
  config.vm.provision "shell",
    inline: "bash /vagrant/config.sh"

end